### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by eatyourpeas** [mysociety/composite_uk_imd#2]
Thank you for this remarkable and thoughtful resource. Is there anyway to use the different weights you describe to calculate deciles/quintiles in the subdomains (Income, Employment, Health, Education, and Crime) or is it only possible to have a composite decile/quintile?

**Comment by ajparsons** [comment]
Sorry, missed this comment! It's only really possible to do the aggregate with this method because the different subdomains aren't really combinable (it only works in composite because the ones they have in common account for such a large amount of the explanation of the total).

But the Income one is in there for the UK index, and the income and employment scores are calculated for the GB index - so those ones you could work with in the downloadable data. 

Otherwise you'll need to find data that exists in all four areas and combine it separately - the different technical documentation explains the underlying factors (but often at least some of them are private datasets sadly).

**Comment by eatyourpeas** [comment]
thank you!
